coop:
  batch_size: 10
  learning_rate: 0.002
  weight_decay: 0.0001
  momentum: 0.9
  epochs: 20
  n_ctx: 8
  ctx_init: ""
  class_token_position: "end"
  csc: false

cocoop:
  cnn_model: "ViT-B/32"
  test_batch_size: 10
  optimizer_configs:
    - prompt_lr: 0.002
      weight_decay: 0.0001
      momentum: 0.9
    - prompt_lr: 0.002
      mlp_lr: 0.002
      weight_decay: 0.0005
      momentum: 0.8
  skip_tests: [true, true, false]
  #train_base_checkpoint_path: "./bin/cocoop/NO_KL_ADV_IMG_FT_8_CTX_20250522_140018.pth"
  prompt_learner_opt:
    n_ctx: 8
    ctx_init: ""
    class_token_position: "end"
    csc: false
  kl_loss_opt:
    lambda_kl: [0.1, 0.1]
    using_kl: [true, false]
  adv_training_opt:
    batch_size: 4
    warmup_lambda_adv: 6
    adv_training_epochs: 15
    lambda_adv: 0.2
    grl_lambda: 5
    mlp_opt:
      hidden_dim: 592
      hidden_layers: 3
  base_training_opt:
    batch_size: 10
    warmup_epoch: 2
    warmup_cons_lr: 0.00001
    epochs: 0
  clustering_opt:
    n_clusters: 2
    variance: 0.95
    vision_encoder: "RN50"
    method: "kmeans"
