coop:
  batch_size: 10
  learning_rate: 0.002
  weight_decay: 0.0001
  momentum: 0.9
  epochs: 20
  n_ctx: 8
  ctx_init: ""
  class_token_position: "end"
  csc: false

cocoop:
  cnn_model: "ViT-B/32"
  test_batch_size: 10
  optimizer_configs:
    - prompt_lr: 0.002
      weight_decay: 0.0001
      momentum: 0.9
    - prompt_lr: 0.002
      mlp_lr: 0.002
      weight_decay: 0.0005
      momentum: 0.8
  skip_tests: [true, true, false]
  train_base_checkpoint_path: "./bin/good_starting_point/base_kl.pth"
  prompt_learner_opt:
    n_ctx: 8
    ctx_init: ""
    class_token_position: "end"
    csc: false
  kl_loss_opt:
    lambda_kl: [0.1, 0.1]
    using_kl: [true, false]
  adv_training_opt:
    adv_training_epochs: 10
    batch_size: 10
    warmup_lambda_adv: 6
    lambda_adv: 0.5
    grl_lambda: 1
    mlp_opt:
      hidden_structure: [2368, 1024, 512, 256, 128]
    prompt_learner_warmup_epochs: 11
  base_training_opt:
    epochs: 0
    batch_size: 10
    warmup_epoch: 0
    warmup_cons_lr: 0.00001
  clustering_opt:
    n_clusters: 2
    variance: 0.95
    vision_encoder: "RN50"
    method: "kmeans"
    use_random_clustering: false
