coop:
  batch_size: 10
  learning_rate: 0.002
  weight_decay: 0.0001
  momentum: 0.9
  epochs: 20
  n_ctx: 8
  ctx_init: ""
  class_token_position: "end"
  csc: false

cocoop:
  pat: false
  report: true
  cnn_model: "ViT-B/16"
  test_batch_size: 10
  pseudo_base_ratio: 0.8
  optimizer_configs:
    - prompt_lr: 0.002
      weight_decay: 0.0001
      momentum: 0.9
    - prompt_lr: 0.002
      mlp_lr: 0.005
      weight_decay: 0.0005
      momentum: 0.8
  skip_tests: [true, false, false]
  train_base_checkpoint_path: "./bin/cocoop/after_first_train_from_yaml_adv_v2_20250722_074504.pth"
  prompt_learner_opt:
    n_ctx: 4
    ctx_init: ""
    class_token_position: "end"
    csc: false
  kl_loss_opt:
    lambda_kl: [0.15, 0.1]
    using_kl: [true, false]
    double_datasets_kl: true
    rotation_period: 4
  adv_training_opt:
    adv_training_epochs: 10
    batch_size: 10
    warmup_lambda_adv: 10
    lambda_adv: 0.5
    grl_lambda: 1
    mlp_opt:
      hidden_dim: 512
      dropout: 0.35
    prompt_learner_warmup_epochs: 5
    ignore_no_improvement: true
    gaussian_noise: 0.2
  base_training_opt:
    batch_size: 16
    warmup_epoch: 2
    warmup_cons_lr: 0.00001
    epochs: 10
  clustering_opt:
    n_clusters: 4
    variance: 0.95
    vision_encoder: "ViT-B/32"
    clustering_type: "semantic"
