from training_systems.training_methods.Adversarial import Adversarial
from training_systems.training_methods.KLCoCoOp import KLCoCoOp
from training_systems.training_methods.KLCoCoOpV2 import KLCoCoOpV2
from training_systems.training_methods.BaseCoCoOp import BaseCoCoOp
